name: Backend CI
on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    paths:
      - 'backend/**'
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -U pip
          pip install -r requirements.txt
          pip install fastapi uvicorn pytest pytest-cov
      - name: Run tests
        run: |
          . venv/bin/activate
          pytest -q
